#!/usr/bin/env bash

if pgrep -f "mongod" > /dev/null
then
  echo "MongoDB running"
else
  echo "Starting MongoDB"
  mongod &> /dev/null &
fi

if pgrep -f "rabbitmq-server" > /dev/null
then
  echo "RabbitMQ running"
else
  echo "Starting RabbitMQ"
  rabbitmq-server &> /dev/null &
fi

if [ -z "$1" ]
  then
    WORKERS=1
  else
    WORKERS=$1
fi

for i in `seq 1 $WORKERS`
do
  echo "Starting worker $i"
  node worker &> /dev/null &
done

echo "Starting web server"
node web &> /dev/null &

echo "Running web_crawler with $WORKERS workers"
echo "To start more workers, use 'node worker'"
